name: Pre-commit checks

on: pull_request

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: install-poetry/action@v1

      - name: Install dependencies
        run: poetry install

      - name: Cache pre-commit post-installation image
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit on changed files
        run: pre-commit run --files $(git diff --name-only HEAD^)
